version: '3.8'
services:
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:alpine-slim"
    ports:
      - "80:80"
    volumes:
      #- ./nginx.conf:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
    #networks:
    #  - web_network
    networks:
      - load-balancer
#networks:
#  web_network:
#    external: true
networks:
  load-balancer:
    driver: bridge
    name: server_load_balancer
